import org.testng.annotations.*;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'Karanjit_Singh' at '13/2/17 11:41 AM' with Gradle 3.1
 *
 * @author Karanjit_Singh, @date 13/2/17 11:41 AM
 */
public class IntToBinaryTest {
    @DataProvider(name="IntegerCases")
    private Object[][] relevantIntegers() {
        return new Object[][]{{123},
                {12},
                {3456},
                {1}};
    }

    @Test (dataProvider = "IntegerCases")
    public void WhenUserGiveStringInput(int i) {

        IntToBinary classUnderTest = new IntToBinary();
        assertEquals(classUnderTest.toBinaryString(i),i, "someLibraryMethod should return 'true'");
    }
}
